env:
  global:
    - PYFUNCEBLE_AUTO_CONFIGURATION: PyFunceble

language:       python

python:
  - "3.6"

matrix:
  fast_finish:  true

script:
  - python3 setup.py test && python3 setup.py install && PyFunceble -d github.com  && PyFunceble -f .travis/list_to_test && PyFunceble --adblock -f .travis/adblock_to_test && deactivate
  - python3 setup.py install --record files.txt && rm -fr $(cat files.txt) && pip install git+https://github.com/funilrys/PyFunceble.git@modulo-dev#egg=PyFunceble && PyFunceble -d github.com
