env:
  matrix:
    - PYTHON_VERSION="3.6.0"
    - PYTHON_VERSION="3.6.1"
    - PYTHON_VERSION="3.6.2"
    - PYTHON_VERSION="3.6.3"
    - PYTHON_VERSION="3.6.4"
    - PYTHON_VERSION="3.6.5"
    - PYTHON_VERSION="3.6.6"
    - PYTHON_VERSION="3.7.0"
    - PYTHON_VERSION="3.7.1"
  global:
    - PYFUNCEBLE_AUTO_CONFIGURATION="PyFunceble"

language: generic
sudo: false

os:
  - linux
  - osx

matrix:
  fast_finish: true

install:
  - export PATH="${HOME}/miniconda/bin:${PATH}"
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python="${PYTHON_VERSION}"
  - source activate test-environment
  - python -VV
  - pip --version
  - pip install pylint coverage coveralls

script:
  - python setup.py install
  - coverage run setup.py test
  - echo "Lint PyFunceble" && pylint PyFunceble
  - echo "Lint tests" && pylint tests/*.py
  - PyFunceble -v
  - PyFunceble --clean
  - PyFunceble --clean-all
  - rm -R output && PyFunceble --directory-structure && ls -al output
  - PyFunceble -ex -d github.com
  - PyFunceble -ex -s -f .travis/lists/simple
  - PyFunceble -ex --syntax -f .travis/lists/simple
  - PyFunceble -ex -f .travis/lists/simple --json --plain
  - PyFunceble -ex -f .travis/lists/simple # Normally, all inactive are not tested anymore.
  - PyFunceble -ex --database -f .travis/lists/simple # And they will be retested.
  - PyFunceble -ex --database --filter ".info$" -f .travis/lists/simple # Only .info domains should be tested.
  - PyFunceble -ex --adblock -a -f .travis/lists/adblock
  - PyFunceble -ex --link https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
  - python .travis/complementary/basic_example.py
  - python .travis/complementary/basic_example_syntax.py
  - python .travis/complementary/advanced_example.py
  - python .travis/complementary/loop_example.py
  - python .travis/complementary/custom_configuration.py

after_success:
  - coveralls

deploy:
  provider: pypi
  user: funilrys
  password:
    secure: BB0saenk1aZs00PJD/3lhv6540+6COp5AdEgeWolhbN3mvIshlfojfSx7a50rLDOKo8DjsNjoxDu4IRq1iskySpzihMtPCnYcD+eLSiUeh9hSKHiXs+AaAJlBfGXzu5c4Vv1IcEJ3bUz4fK51IcrfdrTmuLdAEPtf89osONIOYrt/B8LIqOAdJD4QXGmg2VhcEVTe9YUcsrwNIUQRqLW7oBZiD481XvmExrR6wRYudOzC+QHngyPYh5nqzsK6WlBSp23by48l7mA82RVcPG5dJHNjsEZvnv5hjNl9IPc9ITpkgh78RE0ThqZVa1gPOM5HUgDBprLRRLRgzFvaiv3KnWPJ0X4BIdnxk6au/WpC7jz102v17tBaJh/JBCQUujnSxKusyNYqpcOUET1f14wdwdwnN634XPLnMz6Q4rEIUYwBto4ilwKp/zEW7PYYDrLZbPlsvG++AvjOdh/tNskkGa/AdGbrcs4t6vkd9X3TTsl/MVRW7r/3FY3MJp/3RpfJP9LA8qUEl+gcmfaXccrc9AnLyUuAlqxL/1ENlICruO978ejoML2sZJuU6BjPjysfPG+9fq4q91DR6N6vPbCII0yZdDabm/sGk4rwALI/xwU2T0IQ0lR9lMAPPTNcBbj/if1ZO3W9vCaoLZQ/o80fNHpkTfRGk0bbGpSVziACrc=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    all_branches: true
    condition: "${TRAVIS_BRANCH} =~ ^dev|master$"

notifications:
  on_success: change
  on_failure: always
