env:
  - PYFUNCEBLE_AUTO_CONFIGURATION="PyFunceble"
  - PYTHON_VERSION="3.6.0"
  - PYTHON_VERSION="3.6.1"
  - PYTHON_VERSION="3.6.2"
  - PYTHON_VERSION="3.6.3"
  - PYTHON_VERSION="3.6.4"
  - PYTHON_VERSION="3.6.5"
  - PYTHON_VERSION="3.6.6"
  - PYTHON_VERSION="3.7.0"
  - PYTHON_VERSION="3.7.1"

language: generic
sudo: false

cache:
  directories:
    - ${HOME}/miniconda

os:
  - linux
  - osx

matrix:
  fast_finish: true

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - export PATH=${HOME}/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=${TRAVIS_PYTHON_VERSION} pip
  - source activate test-environment
  - pip3 install --upgrade pip
  - pip3 install pyfunceble-dev
  - pip3 install pylint coverage coveralls pip-autoremove

script:
  # Everything is into one line because we want the test to fail if one of those command fails.
  - PyFunceble -ex -d github.com  && PyFunceble -ex -f .travis/list_to_test && PyFunceble -ex --adblock -f .travis/adblock_to_test
  - pip-autoremove pyfunceble-dev -y && coverage run setup.py test && python3 setup.py install && PyFunceble -ex -d github.com  && PyFunceble -ex -f .travis/list_to_test && PyFunceble -ex --adblock -f .travis/adblock_to_test
  - echo "Lint PyFunceble" && pylint PyFunceble && echo "Lint tests" && pylint tests/*.py

after_success:
  - coveralls

notifications:
  on_success: change
  on_failure: always
